website/main_app/urls.py
# from django.contrib import admin
from django.urls import path
from . import views

app_name = "main_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('women_rights/', views.women_rights, name='women_rights'),

    path('register/', views.register, name="register"),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.login_request, name="login"),

    path('emergency_contact/', views.emergency_contact, name="emergency_contact"),
    path("create_contact/", views.create_contact, name="create_contact"),
    path("update_contact/<str:pk>/", views.update_contact, name="update_contact"),
    path("delete_contact/<str:pk>/", views.delete_contact, name="delete_contact"),
    path("emergency/", views.emergency, name="emergency"),

    path("news/", views.news, name="news"),


    path("city_map/", views.city_map, name="city_map"),
    path("find_me/", views.find_me, name="find_me"),
    path("women_laws/", views.women_laws, name="women_laws"),

    path("helpline_numbers/", views.helpline_numbers, name="helpline_numbers"),
    path("scholarships/", views.scholarships, name="scholarships"),
    # path('admin/', admin.site.urls),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

website/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="contact", null=True)
    name = models.CharField(max_length=100)
    phone = models.IntegerField()
    email = models.EmailField()

    Father = 'Father'
    Mother = 'Mother'
    Brother = 'Brother'
    Sister = 'Sister'
    Husband = 'Husband'
    Friend = 'Friend'
    Relative = 'Relative'
    Other = 'Other'
    relations = (
        (Father, 'Father'),
        (Mother, 'Mother'),
        (Brother, 'Brother'),
        (Sister, 'Sister'),
        (Husband, 'Husband'),
        (Friend, 'Friend'),
        (Relative, 'Relative'),
        (Other, 'Other'),
    )
    relation = models.CharField(max_length=10, choices=relations, default=Other)
    def __str__(self):
        return self.name

website/main_app/forms.py
from django.forms import ModelForm
from .models import contact
from django import forms


class ContactForm(ModelForm):
    class Meta:
        model = contact
        fields = ['name', 'phone', 'email', 'relation']
        Father = 'Father'
        Mother = 'Mother'
        Brother = 'Brother'
        Sister = 'Sister'
        Husband = 'Husband'
        Friend = 'Friend'
        Relative = 'Relative'
        Other = 'Other'
        relations = (
            (Father, 'Father'),
            (Mother, 'Mother'),
            (Brother, 'Brother'),
            (Sister, 'Sister'),
            (Husband, 'Husband'),
            (Friend, 'Friend'),
            (Relative, 'Relative'),
            (Other, 'Other'),
        )
        widgets = {
            'relation': forms.Select(choices=relations, attrs={'class': 'form-control'}),
        }

website/main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import ContactForm
from .models import contact
from django.contrib.auth.models import User
from .SmsSender import sendSms
from .Scraper import news_fetch, write_news
from os import getcwd
from .mail import send_mail
import sys
from sys import platform


# Create your views here.
def home(request):
    context = {

    }
    return render(request, 'main_app/home.html', context)


def women_rights(request):
    return render(request, 'main_app/women_rights.html', {'title': 'women_rights'})


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f"New Account Created Successfully: {username}")
            login(request, user)
            messages.info(request, f"Logged in as {username}")
            return redirect('main_app:home')
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: form.error_messages[msg]")

    form = UserCreationForm
    return render(request, 'main_app/register.html', context={'form': form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main_app:home")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(
                    request, f"Successfully logged in as {username} !")
                return redirect("main_app:home")
            else:
                messages.error(
                    request, f"Invalid username or password {username} ")
        else:
            messages.error(request, "Invausername or password  ")

    form = AuthenticationForm
    return render(request, "main_app/login.html", {'form': form})

# @login_required(login_url='login/')


def emergency_contact(request):
    users = User.objects.all()
    curr = 0
    for user in users:
        if request.user.is_authenticated:
            curr = user
            break
    if curr == 0:
        return redirect("main_app:login")
    user = curr
    contacts = contact.objects.filter(user=user)
    total_contacts = contacts.count()
    context = {'contacts': contacts,
               'total_contacts': total_contacts, 'user': user}

    return render(request, 'main_app/emergency_contact.html', context)


def create_contact(request):
    users = User.objects.all()
    curr = 0
    for user in users:
        if request.user.is_authenticated:
            curr = user
            break
    inst = contact(user=curr)
    form = ContactForm(instance=inst)
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=inst)
        if form.is_valid():
            form.save()
            messages.info(request, f"New contact created successfully!!")
            name = form.cleaned_data.get('name')
            mail = form.cleaned_data.get('email')
            message = "Hello, " + name + \
                "\nYour contact information has been saved as emergency contact by " + curr.username + "."
            send_mail(mail, message)
            messages.info(request, f"An email has been sent to your contact!!")
            return redirect('main_app:emergency_contact')

        messages.error(request, f"Invalid username or password")
    # messages.error(request, f"Invalid contact!!")
    context = {'form': form}
    return render(request, 'main_app/create_contact.html', context)


def update_contact(request, pk):
    users = User.objects.all()
    curr = 0
    for user in users:
        if request.user.is_authenticated:
            curr = user
            break

    curr_contact = contact.objects.get(id=pk)
    name = curr_contact.name
    form = ContactForm

    if request.method == 'POST':
        form = ContactForm(request.POST, instance=curr_contact)
        if form.is_valid():
            form.save()
            messages.error(request, f"{name} updated successfully!!")
            name = form.cleaned_data.get('name')
            mail = form.cleaned_data.get('email')
            message = "Hello, " + name + "\nYour contact information as emergency contact by " + \
                curr.username + " has been updated."
            send_mail(mail, message)
            messages.info(request, f"An email has been sent to your contact!!")

            return redirect('main_app:emergency_contact')

    context = {'form': form}
    return render(request, 'main_app/create_contact.html', context)


def delete_contact(request, pk):
    curr_contact = contact.objects.get(id=pk)
    name = curr_contact.name
    if request.method == "POST":
        curr_contact.delete()
        messages.error(request, f"{name} deleted successfully!!")
        return redirect('main_app:emergency_contact')

    context = {'item': curr_contact}
    return render(request, 'main_app/delete_contact.html', context)


def emergency(request):
    users = User.objects.all()
    curr = 0
    for user in users:
        if request.user.is_authenticated:
            curr = user
            break
    if curr == 0:
        return redirect("main_app:login")
    user = curr
    contacts = contact.objects.filter(user=user)
    emails = []
    for j in contacts:
        emails.append(j._meta.get_field("email"))
    name = user.username
    message = name+" is in emergency situation and need your help immediately!!"

    errors = ""
    try:
        sendSms("8350815015", message)
    except:
        errors += "Message not send to 8350815015"
        pass
    try:
        sendSms("7696043017", message)
    except:
        errors += "Message not send to 7696043017"
        pass

    for c in contacts:
        send_mail(c.email, message)

    admin = [["Parikh", "8350815015"], ["Ankit", "1234567890"]]
    context = {'contacts': contacts, 'admin': admin,
               'error': errors, 'emails': emails}

    return render(request, 'main_app/emergency.html', context)


def news(request):
    if platform == "linux" or platform == "linux2":
        news_fetch()
        write_news()
    return render(request, 'main_app/news.html', {'title': 'news'})


def city_map(request):
    return render(request, 'main_app/city_map.html', {'title': 'city_map'})


def find_me(request):
    return render(request, 'main_app/find_me.html', {'title': 'current location'})


def women_laws(request):
    return render(request, 'main_app/women_laws.html', {'title': 'women_laws'})


def helpline_numbers(request):
    return render(request, 'main_app/helpline_numbers.html', {'title': 'helpline_numbers'})

def scholarships(request):
    return render(request, 'main_app/scholarships.html', {'title': 'scholarships'})

website/main_app/templates/main_app/common.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
    <title>Empower Her</title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script type = "text/javascript" src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    </head>

    <body>

        <nav class="navbar navbar-expand-lg" style="background-color:ff84a7; height:100px; padding:None;" >
            <img class="materialboxed" style="margin:10px" height="70" width="70" src="{% static 'Images/new_logo.png' %}">
            <script>
                $(document).ready(function(){
                    $('.materialboxed').materialbox();
                });

            </script>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">

              <li class="nav-item" style="padding-left:10px">
                  <a class="nav-link tooltipped" data-position="right" data-tooltip="Move To Home" href="/home"><h5>Home</h5></a>
              </li>

               <!-- Dropdown Trigger -->
              <li class="nav-item" style="padding-left:10px">
                  <a class="dropdown-trigger nav-link tooltipped" data-position="right" data-tooltip="Find In Maps" href='#' data-target='dropdown1'><h5>☰ Maps </h5></a>
              </li>
              <!-- Dropdown Structure -->
              <ul id='dropdown1' class='dropdown-content' style="background-color: #f1f1f1;">
                
                <li><a style="color: #000000;" href="/city_map" class="tooltipped" data-position="right" data-tooltip="Search In City Map">Find in city</a></li>
                <li class="divider" tabindex="-1"></li>
                <li><a style="color: #000000;" href="/find_me" class="tooltipped" data-position="right" data-tooltip="Get Your Current Location">Find Me!</a></li>
              </ul>
              <script>
                  $('.dropdown-trigger').dropdown({
                      coverTrigger:false
                  });
              </script>

               <!-- Dropdown Trigger -->
              <li class="nav-item" style="padding-left:10px">
                  <a class="dropdown-trigger nav-link tooltipped" data-position="right" data-tooltip="Get Women Related Info" href='#' data-target='dropdown2'><h5>☰ Women </h5></a>
              </li>
              <!-- Dropdown Structure -->
              <ul id='dropdown2' class='dropdown-content' style="background-color: #f1f1f1; ">
                <li><a style="color: #000000;" href="/scholarships" class="tooltipped" data-position="right" data-tooltip="Women Scholarships">Scholarships</a></li>
                <li class="divider" tabindex="-1"></li>
                <li><a style="color: #000000;" href="/women_rights" class="tooltipped" data-position="right" data-tooltip="Women Legal Rights In India">Women Rights</a></li>
                <li class="divider" tabindex="-1"></li>
                <li><a style="color: #000000;" href="/women_laws" class="tooltipped" data-position="right" data-tooltip="Laws For Women">Women Laws </a></li>
                <li class="divider" tabindex="-1"></li>
                <li><a style="color: #000000;" href="/helpline_numbers" class="tooltipped" data-position="right" data-tooltip="Get To Nearest Helpline">Women Helpline Numbers</a></li>
                <li class="divider" tabindex="-1"></li>
                <li><a style="color: #000000;" href="/news" class="tooltipped" data-position="right" data-tooltip="See Women Issues">Quick Glance</a></li>
              </ul>
              <script>
                  $('.dropdown-trigger').dropdown({
                      coverTrigger:false
                  });
              </script>



              <li class="nav-item">
                <a class="nav-link tooltipped" data-position="right" data-tooltip="See Emergency Contacts" href="/emergency_contact"><h5>Emergency Contacts</h5></a>
              </li>
            </ul>

            <ul>
              {% if user.is_authenticated %}
                  <li>
                      <a class="nav-link nav-item dropdown-trigger tooltipped navbar-nav mr-auto" style="color:white;" href="#" data-target="dropdown3" data-position="left" data-tooltip="Hello, {{user.username}}"><h5>{{user.username}}</h5></a>
                  </li>
                <ul id='dropdown3' class='dropdown-content' style="background-color: #f1f1f1;">
                    <li><a style="color: #000000;" href="/logout" class="tooltipped" data-position="left" data-tooltip="Good Bye">Logout</a></li>
                </ul>
              <script>
                  $('.dropdown-trigger').dropdown({
                      coverTrigger:false
                  });
              </script>
              {% else %}
                  <li>
                      <a class="nav-link nav-item dropdown-trigger tooltipped navbar-nav mr-auto" data-position="left" data-tooltip="Welcome, To Suraksha" style="color:white;" href="#" data-target="dropdown4" data-position="left" data-tooltip="User login/register"><h5> User</h5></a>
                  </li>
                <ul id='dropdown4' class='dropdown-content' style="background-color: #f1f1f1;">
                  <li class="nav-item">
                    <a style="color: #000000;" class="tooltipped" data-position="left" data-tooltip="Register New Account" href="/register">Register</a>
                  </li>
                  <li class="divider" tabindex="-1"></li>
                  <li class="nav-item">
                    <a style="color: #000000;"  href="/login" class="tooltipped" data-position="left" data-tooltip="Login to Account">Login</a>
                  </li>
                </ul>
              <script>
                  $('.dropdown-trigger').dropdown({
                      coverTrigger:false
                  });
              </script>
              {% endif %}
              <li><a class="nav-link tooltipped nav-item" data-position="left" data-tooltip="Click only in emergency situation. It will send help message to your emergency contacts." href="/emergency"><h5><strong>EMERGENCY !!</strong></h5></a></li>

            </ul>
             <script>
                $(document).ready(function(){
                    $('.tooltipped').tooltip();
                  });
            </script>
          </div>
        </nav>

        {% if messages %}
            {% for message in messages %}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded',
                displayLength:4000});</script>
            {% endfor %}
        {% endif %}


            {% block content %}

            {% endblock %}

        <footer class="page-footer" style="background-color:#ff84a7;">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h4 class="white-text">Our Aim</h4>
                <p class="grey-text text-lighten-4"><h4>Towards a better and safer India.</h4></p>
                
              </div>
              <div class="col l4 offset-l2 s12">
                <ul>
                  <li><a class="white-text tooltipped" data-position="right" data-tooltip="Back To Home" href="/home"><i class="material-icons small">home</i></a></li>
                  
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
          </div>
        </footer>


    </body>
</html>

website/main_app/templates/main_app/create_contact.html
<!DOCTYPE html>
{% extends "main_app/common.html" %}
{% load static %}

<html lang="en">
    {% block content %}
    <body style="background-color:white;">
        <br>
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <br>
                <button style="color:white; background-color:black;" class="btn" name="submit" type="submit">Create</button>
            </form>

        </div>
    </body>
    <br><br><br><br>
    <br><br><br>
    {% endblock %}



</html>

website/main_app/templates/main_app/delete_contact.html
{%  extends 'main_app/common.html' %}
{% load static %}
{% block content %}
<body style="background-color:#white;">
<br><br>

	<div class="container">
		<br>
		<div class="row">
			<div class="col-md-6">
				<div class="card card-body" style="background-color:#ECEFF1;">


					<p>Are you sure you want to delete this contact? "{{item}}"?</p>

					<form action="{% url 'main_app:delete_contact' item.id  %}" method="POST">

						{% csrf_token %}
						<a style="color:white; background-color:black;" class="btn btn-warning" href="{% url 'main_app:emergency_contact' %}">Cancel</a>

						<input style="color:white; background-color:black;" class="btn btn-danger" type="submit" name="Yes">
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br>

{% endblock %}

website/main_app/templates/main_app/emergency.html
<!DOCTYPE html>
{% extends "main_app/common.html" %}
{% load static %}

<html lang="en">
    
     {% block content %}
    <body style="height:1000px; max-width:100%; background-color:#ECEFF1;">
    <div class="container" style="height:65%; max-width:100%">

    <h1 style="color:red; text-decoration:underline;">Emergency Situation!!</h1>
        <br>
        {% for contact in contacts %}
            <h4 style="color:black">Message deleivered to {{contact.name}} at {{contact.phone}}</h4>
            <h4 style="color:black">Email deleiverd to {{contact.name}} at {{contact.email}}</h4>
        <br>
        {% endfor %}


    </div>
    </body>

    {% endblock %}



</html>

website/main_app/templates/main_app/emergency_contact.html
{%  extends 'main_app/common.html' %}

{% block content %}

<body style="background-color:white;">
	<br>
	<div class="jumbotron jumbotron-fluid container">
	  <div>
		<h1 class="display-4" style="margin-left:2%;">Emergency Contacts</h1>
		<p class="lead" style="margin-left:2%;">Save your trusted contacts, in emergency situation your emergency contacts are just one button-press away.</p>
	  </div>
	</div>
	<div class="container">

		<div class="row">
			<div class="col-md-7">
				<h6>Total Saved Contacts: {{total_contacts}}</h6>
				<hr><br>

					<a style="color:white; background-color:black;" class="btn btn-primary  btn-sm btn-block" href="{% url 'main_app:create_contact' %}">Create Contact</a>
					<br>
					<table class="table">
						<thead class="thead"  style="color:black; background-color:#E9ECEF;">
							<tr>
								<th>Name</th>
								<th>Phone</th>
								<th>Relation</th>
								<th>Email</th>
								<th>Update</th>
								<th>Delete</th>
							</tr>
						</thead>

						{% for contact in contacts.all %}
							<tbody class="table-striped">
								<tr>
									<td>{{contact.name}}</td>
									<td>{{contact.phone}}</td>
									<td>{{contact.relation}}</td>
									<td>{{contact.email}}</td>
									<td><a style="color:white; background-color:black;" class="btn btn-sm btn-info" href="{% url 'main_app:update_contact' contact.id %}">Update</a></td>
									<td><a style="color:white; background-color:black;" class="btn btn-sm btn-danger" href="{% url 'main_app:delete_contact' contact.id %}">Delete</a></td>
								</tr>
							</tbody>
							<br>
						{% endfor %}

					</table>
			</div>


		</div>
	</div>
</body>
<br><br><br>

{% endblock %}

website/main_app/templates/main_app/find_me.html
<!DOCTYPE html>
{% extends "main_app/common.html" %}
{% load static %}

<html lang="en">
    {% block content %}

    <body style="background-color:#ECEFF1;">
        <div class="container">


        <script src="https://apis.mapmyindia.com/advancedmaps/v1/oehzgx54nik3ur7upodu32splbu6gxw5/map_load?v=1.5"></script>
        <style>
            #map {	margin: 0;	padding: 0;width: 100%;height: 1000px;}
        </style>

        <br>
            <br>
        <h5><strong>Click the button to get your coordinates.</strong></h5>

        <button class="btn btn-outline-info" id="find-me" onclick="getLocation()" style="color:white; background-color:black;">Get Location</button>

        <p id="demo"></p>

        <div id="map"></div>

            <br><br>

        <script>
            var x = document.getElementById("demo");

            var lat = 30;
            var long = 78;
            var icon = L.divIcon({
                 className: 'my-div-icon',
                 html: "<img class='map_marker'  src=" + "'https://maps.mapmyindia.com/images/2.png'>" ,
                 iconSize: [10, 10],
                 popupAnchor: [12, -10]
            });/*function that creates a div over a icon and display content on the div*/

            var apikey = 'd25ac72e7a1e43b8a2d3c939895889d1';
            var api_url = 'https://api.opencagedata.com/geocode/v1/json'



            function showPosition(position) {
                x.innerHTML="<hr>Your Latitude: " + position.coords.latitude +
                "<br>Your Longitude: " + position.coords.longitude;
                lat = position.coords.latitude;
                long = position.coords.longitude;

                var latitude = lat;
                var longitude = long;
                var title = "Your Location is -> ";
                var request_url = api_url
                    + '?'
                    + 'key=' + apikey
                    + '&q=' + encodeURIComponent(latitude + ',' + longitude)
                    + '&pretty=1'
                    + '&no_annotations=1';

                var request = new XMLHttpRequest();
                request.open('GET', request_url, true);

                request.onload = function() {
                // see full list of possible response codes:
                // https://opencagedata.com/api#codes

                if (request.status == 200){
                  // Success!
                  var data = JSON.parse(request.responseText);

                  title+=data.results[0].formatted;

                  var map=new MapmyIndia.Map("map",{ center:[lat, long], zoomControl: true, hybrid:true, search:true, location:true});
                  var position = new L.LatLng(lat, long);/*The WGS location object*/
                  var mk = new L.Marker(position, {icon: icon, title: title});/*marker with a custom icon */
                  mk.bindPopup(title);
                  map.addLayer(mk);

                } else if (request.status <= 500){
                  // We reached our target server, but it returned an error

                  console.log("unable to geocode! Response code: " + request.status);
                  var data = JSON.parse(request.responseText);
                  console.log(data.status.message);
                } else {
                  console.log("server error");
                }
                };

                request.onerror = function() {
                    // There was a connection error of some sort
                    console.log("unable to connect to server");
                };

                request.send();  // make the request


            }

            function getLocation() {
              if (navigator.geolocation) {
                navigator.geolocation.watchPosition(showPosition);
              } else {
                x.innerHTML = "Geolocation is not supported by this browser.";
              }
            }


        </script>
        </div>
    </body>

    {% endblock %}



</html>

website/main_app/templates/main_app/login.html
<!DOCTYPE html>
{% extends "main_app/common.html" %}
{% load static %}

<html lang="en">
    {% block content %}
    <body style="background-color:white;">

        <div class="container">
            <br>
            <div class="jumbotron jumbotron-fluid"  style="background-color:#ECEFF1;">
              <div class="container">
                <h1 class="display-4">Welcome, back</h1>
                <p class="lead">Login to your registered account.</p>
              </div>
            </div>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <br>
                <button style="color:white; background-color:black;" class="btn" type="submit">Login</button>
            </form>
            <br>
            No account yet,  <a href="/register"><strong>Create New Account</strong></a>.

        </div>
    </body>
    <br>

    {% endblock %}



</html>